---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  product_name: chef
  product_version: 17
  install_strategy: upgrade
  deprecations_as_errors: true

verifier:
  name: inspec

platforms:
  - name: win2012r2
    driver_config:
      box: mwrock/Windows2012R2
      gui: false

suites:
  - name: default
